version: '3.4'

services:
  api:
    build:
      context: .
      target: api
    ports:
      - "8000:80"
    depends_on:
      - db
  ui:
    build:
      context: .
      target: ui
    ports:
      - "8080:80"
    depends_on:
      - api
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:8889"
    environment:
      MYSQL_TCP_PORT: "8889"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "moore-market"
      MYSQL_USER: "moore-market"
      MYSQL_PASSWORD: "password"

volumes:
  db_data: